apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pv-kind
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  # we don't have a selector here because there's no a persistent volume already in existents with a set of labels we want to match it
  storageClassName: standard
